#!/usr/bin/env python3

from os      import listdir
from os.path import isfile, isdir, join
import re
import sys

if len(sys.argv) < 2:
    print("\nyou need argument\n")
    exit()

target_dir = sys.argv[1]

def read(file_path):
    if(re.match(".+\.groovy$", file_path)):
        file    = open(file_path, "r")
        content = file.read()
        file.close()
        return content
    return ''

def lint_dir(path):
    if(isfile(path)):
        print(f"file: {path}")
        lint_groovy(path)
    elif(isdir(path)):
        print(f"dir: {path}")
        onlyfiles = [join(path, f) for f in listdir(path)]
        for x in onlyfiles:
            lint_dir(x)
    else:
        pass

def lint_groovy(path):
    file_text = read(path)
    lines = [x.strip() for x in file_text.split('\n') if x != '']
    print(lines)
    orphans = []

    for line in lines:
        if(re.search("import ", line)):
            lsp = line.split(".")
            orphans.append(lsp[len(lsp) - 1])
            print(f"-- {line}")
    print(f"-- {orphans}")
    for orphan in orphans:
        match_result = re.search(f"{orphan}.+\n", file_text)
        if(match_result): 
            matched_line = match_result.group(0).replace('\n', '')
            print(f"{orphan} found | {matched_line}")
        else:
            print(f"{orphan} missing!")

    # parse content

lint_dir(target_dir)
